server:
  port: 3000

spring:
  application:
    name: crowdfunding-redis-provider
  redis:
    host: 192.168.49.128

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
