server:
  port: 2000

spring:
  application:
    name: crowdfunding-mysql-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_crowd?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    name: mydb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka


mybatis:
 mapper-locations: classpath*:/mybatis/mapper/*Mapper.xml

logging:
  com.crowdfunding.crowd.mapper: debug
  com.crowdfunding.crowd.test: debug
